env:
   global:
     - CONAN_USERNAME: "helmesjo"
     - CONAN_LOGIN_USERNAME: "helmesjo"
     - CONAN_CHANNEL: "stable" # because of bug in conan-package-tools, we always upload packages as stable
     - CONAN_UPLOAD: "https://api.bintray.com/conan/helmesjo/public-conan"
     - CONAN_REMOTES: "https://api.bintray.com/conan/helmesjo/public-conan,https://api.bintray.com/conan/bincrafters/public-conan"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 0

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
matrix:
   include:
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
